//base code generated by ChatGPT
"use client";
import React, { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function Chatbot() {
  const [messages, setMessages] = useState<{text: string, sender: string}[]>([]);
  const [input, setInput] = useState("");

  const handleSend = () => {    
    if (!input.trim()) return;
    setMessages([...messages, { text: input, sender: "user" }]);
    setInput("");
  };

  return (
    <div className="max-w-2xl mx-auto p-6">
      <Card className="p-4 h-[500px] overflow-y-auto border border-gray-300 rounded-xl">
        <CardContent>
          {messages.map((msg, index) => (
            <div key={index} className={`mb-2 ${msg.sender === "user" ? "text-right" : "text-left"}`}>
              <span className="inline-block p-2 bg-gray-200 rounded-lg">
                {msg.text}
              </span>
            </div>
          ))}
        </CardContent>
      </Card>
      <div className="mt-4 flex gap-2">
        <Input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Type a message..."
          className="flex-1"
        />
        <Button onClick={handleSend}>Send</Button>
      </div>
    </div>
  );
}
